<?php

namespace JsonRpcFormatter\Validator;

require_once dirname(__FILE__) . '/../../../../src/JsonRpcFormatter/Validator/StrictArgumentValidator.php';

/**
 * Test class for StrictArgumentValidator.
 * Generated by PHPUnit on 2012-03-26 at 20:58:44.
 */
class StrictArgumentValidatorTest extends \PHPUnit_Framework_TestCase
{

	/**
	 * @var StrictArgumentValidator
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp()
	{
		$this->object = new StrictArgumentValidator;
	}

	/**
	 * @dataProvider validIdProvider
	 */
	public function testIsValidId($id)
	{
		$this->assertTrue($this->object->isValidId($id));
	}

	/**
	 * @dataProvider invalidIdProvider
	 */
	public function testIsNotValidId($id)
	{
		$this->assertFalse($this->object->isValidId($id));
	}

	public function validIdProvider()
	{
		return array(
			array(200),
			array("test")
		);
	}

	public function invalidIdProvider()
	{
		return array(
			array(0.356),
			array(null),
			array(new \stdClass),
			array(array("test")),
			array(fopen("php://memory", "r")),
			array(true)
		);
	}

}

